### ISSUE TITLE
Undefined function 'prctile' for input arguments of type 'double'.

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/rss#2]
This is the first error I got when I try to run `example1.m`. I don't see this function defined anywhere in the repository or in any of the [installed packages](https://github.com/stephenslab/rss/wiki/RSS-via-MCMC) (e.g., lightspeed).

**Comment by xiangzhu** [comment]
The function `prctile` requires the [Statistics and Machine Learning Toolbox](http://www.mathworks.com/help/stats/index.html). This function computes the [percentiles](http://www.mathworks.com/help/stats/prctile.html) of a dataset.

```
>> which prctile
/software/matlab-2013b-x86_64/toolbox/stats/stats/prctile.m
```

This function is not used in any `rss` subroutines. Users can comment [line 21-22](https://github.com/stephenslab/rss/blob/master/examples/example1.m#L22) in `example1.m` out if the require toolbox is not available.
