### ISSUE TITLE
One question on the "theta shrinkage"

### ISSUE THREAD

**Issue by privefl** [stephenslab/rss#5]
I'm referring to 
https://github.com/stephenslab/rss/blob/6e9c8f08e82996ee1364f65dec491d84b6bcac26/misc/get_corr.m#L76-L77
and
https://github.com/stephenslab/rss/blob/6e9c8f08e82996ee1364f65dec491d84b6bcac26/misc/get_corr.m#L139

theta seems to be very small for all sample sizes, even small ones like 100; I'm therefore wondering if this has any effect at all?

Thanks,
Florian

**Comment by xiangzhu** [comment]
@privefl  Thanks for your question.

The shrinkage (together with an induced sparsity) actually happens in Lines 116-129 of `get_corr.m`.

Please see https://github.com/stephenslab/rss/blob/master/misc/get_corr.m#L114-L129.

Here `theta` is a parameter relating to mutation, taken from Li & Stephens (2003).

**Comment by privefl** [comment]
Yes, there are two shrinkages used here: one based on distance between variants, and one based on sample size.
I am just wondering if the one on the sample size has any effect given the small values of `theta`.

**Comment by stephens999** [comment]
I think it is hard to say without assessing it empirically. With big
matrices even small changes can have big effects in principle.

**Comment by xiangzhu** [comment]
> Yes, there are two shrinkages used here: one based on distance between variants, and one based on sample size.
> I am just wondering if the one on the sample size has any effect given the small values of `theta`.

@privefl  Thanks for your question.

If you want to continue the discussion on the "theta" parameter in the LD shrinkage estimation, please open a new issue at https://github.com/stephenslab/ldshrink/issues.

**Comment by privefl** [comment]
I think you can transfer the issue to another repo if you want.
